services:
  mongodb:
    image: mongo:7.0.0
    command: ["--replSet", "myReplicaSet", "--port", "27017", "--keyFile", "/etc/mongo/mongodb-keyfile"]

    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ./.docker/mongodb/db:/data/db
      - ./.docker/mongodb/config:/etc/mongo
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
