version: '3.8'

services:
  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ./.docker/data/mongodb/db:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${DB_ROOT_USERNAME}:${DB_ROOT_PASSWORD}@mongodb:${DB_PORT}/"
      ME_CONFIG_BASICAUTH: false
